# Generated by Django 4.1.3 on 2022-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merk',
            options={'verbose_name_plural': 'Merk'},
        ),
        migrations.AlterModelOptions(
            name='spek',
            options={'verbose_name_plural': 'Spek'},
        ),
        migrations.RemoveField(
            model_name='spek',
            name='body',
        ),
        migrations.AlterField(
            model_name='spek',
            name='detail',
            field=models.TextField(),
        ),
    ]
