# Generated by Django 4.1.3 on 2022-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0002_alter_merk_options_alter_spek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spek',
            name='produk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
