# Generated by Django 4.1.3 on 2022-12-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0003_spek_produk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spek',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Spek'},
        ),
    ]
