# Generated by Django 4.1.3 on 2022-12-24 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hp', '0004_alter_spek_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spek',
            name='nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spek',
            name='produk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
