# Generated by Django 4.1.3 on 2022-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0005_alter_spek_nama_alter_spek_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spek',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
