# Generated by Django 4.1.3 on 2022-12-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hp', '0007_alter_spek_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('phone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='spek',
            name='nama',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
