# Generated by Django 4.1.3 on 2022-12-25 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hp', '0008_info_alter_spek_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone_name',
            new_name='produk',
        ),
        migrations.RemoveField(
            model_name='info',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
        migrations.RemoveField(
            model_name='info',
            name='slug',
        ),
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='merk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hp.merk'),
        ),
        migrations.AddField(
            model_name='info',
            name='nama',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
