# Generated by Django 4.1.3 on 2022-12-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0009_rename_phone_name_info_produk_remove_info_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='merk',
        ),
        migrations.AddField(
            model_name='info',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='nomor',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='produk',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
